version: '3.8'
services:
  postgis:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: octopus
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
